comment:
  image:
    repository: timur8298/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: timur8298/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: timur8298/ui
    tag: latest
  service:
    externalPort: 9292

mongodb:
  usePassword: false
