---
- name: Start reddit
  hosts: all
  become: true
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      state: latest
  - name: Install Docker Module for Python
    pip:
      name: docker
      executable: pip
  - name: Start docker
    docker_container:
      name: reddit
      image: timur8298/otus-reddit:1.0
      ports:
        - "9292:9292"
      state: started
      restart: yes
