version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VER}
    container_name: post_db
    volumes:
      - post_db:/data/db
    networks:
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    image: ${USERNAME}/ui:${SERVICE_VER}
    ports:
      - ${EXT_PORT}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    image: ${USERNAME}/post:${SERVICE_VER}
    container_name: post
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}


  comment:
    image: ${USERNAME}/comment:${SERVICE_VER}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongodb-exporter:
    image: percona/mongodb_exporter:0.37.0
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.23.0
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
