version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
    links:
      - "elasticsearch"


  elasticsearch:
    image: elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net

  kibana:
    image: kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - back_net

networks:
  front_net:
  back_net:
