---
apiVersion: apps/v1
kind: Deployment
metadata: # Блок метаданных деплоя
  name: {{ template "post.fullname" . }}
  labels:
    app: reddit
    component: post
    release: {{ .Release.Name }}
spec: # Блок спецификации деплоя
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: post
      release: {{ .Release.Name }}
  template: # Блок описания POD-ов
    metadata:
      name: post
      labels:
        app: reddit
        component: post
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: post
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: post
          protocol: TCP
        env:
        - name: POST_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
